Repository daily-emotion/back-end, pull requests merged in 2024-12, with the labels that each got.

#4 Chore : Firebase 설정 및 연결 확인
  .gitignore
  build.gradle
  src/main/java/com/dailyemotion/dailyemotion/FirebaseTestController.java
  src/main/java/com/dailyemotion/dailyemotion/config/FirebaseConfig.java
  src/main/resources/application.yml
Labels: 🔧 chore

#6 Feat/domain setup (기본 폴더구조 세팅)
  build.gradle
  src/main/java/com/dailyemotion/DailyEmotionApplication.java
  src/main/java/com/dailyemotion/common/config/FirebaseConfig.java
  src/main/java/com/dailyemotion/common/config/SecurityConfig.java
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/diary/dto/request/DiaryReqDto.java
  src/main/java/com/dailyemotion/diary/dto/response/DiaryResDto.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/entity/BaseTimeEntity.java
  src/main/java/com/dailyemotion/domain/entity/Diary.java
  src/main/java/com/dailyemotion/domain/entity/User.java
  src/main/java/com/dailyemotion/domain/enums/Emotion.java
  src/main/java/com/dailyemotion/domain/enums/Role.java
  src/main/java/com/dailyemotion/domain/enums/SocialType.java
  src/main/java/com/dailyemotion/domain/repository/DiaryRepository.java
  src/main/java/com/dailyemotion/domain/repository/UserRepository.java
  src/main/java/com/dailyemotion/firebase/controller/FirebaseTestController.java
  src/main/java/com/dailyemotion/user/controller/UserController.java
  src/main/java/com/dailyemotion/user/dto/request/UserReqDto.java
  src/main/java/com/dailyemotion/user/dto/response/UserResDto.java
  src/main/java/com/dailyemotion/user/service/UserService.java
Labels: ✨ feat, 🔧 chore

#15 feat : diary-delete 로직 구현
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/repository/DiaryRepository.java
  src/test/java/com/dailyemotion/dailyemotion/diary/DiaryServiceTest.java
Labels: ✨ feat
