Repository daily-emotion/back-end, pull requests merged in 2025-01, with the labels that each got.

#16 feat : diary-read 기능 구현
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/repository/TagRepository.java
  src/test/java/com/dailyemotion/dailyemotion/diary/DiaryServiceTest.java
Labels: ✨ feat

#18 feat : diary-update 기능 구현
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/entity/Diary.java
  src/main/java/com/dailyemotion/domain/repository/TagRepository.java
  src/test/java/com/dailyemotion/dailyemotion/diary/DiaryServiceTest.java
Labels: ✨ feat

#20 feat : diary-get (월간) 기능 구현
  src/main/java/com/dailyemotion/common/errorCode/DiaryErrorCode.java
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/diary/dto/response/DiaryGetResDto.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/repository/DiaryRepository.java
  src/test/java/com/dailyemotion/dailyemotion/diary/DiaryServiceTest.java
Labels: ✨ feat

#26 Chore/docker setup
  .gitignore
  build.gradle
  docker-compose.yml
  dockerfile
  src/main/java/com/dailyemotion/diary/repository/DiaryRepository.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/entity/Diary.java
  src/main/java/com/dailyemotion/tag/repository/TagRepository.java
  src/main/java/com/dailyemotion/tag/service/TagService.java
  src/main/java/com/dailyemotion/user/oAuth2/CustomOAuth2UserService.java
  src/main/java/com/dailyemotion/user/repository/UserRepo.java
  src/main/java/com/dailyemotion/user/repository/UserRepository.java
  src/main/java/com/dailyemotion/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/dailyemotion/dailyemotion/diary/DiaryServiceTest.java
Labels: 🔧 chore, 🧪 test

#27 [Refactor] OAuth Setting
  src/main/java/com/dailyemotion/user/handler/CustomSuccessHandler.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: 🔧 chore, ♻️ refactor

#29 Test/diary controller
  src/main/java/com/dailyemotion/common/config/SecurityConfig.java
  src/main/java/com/dailyemotion/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/diary/service/DiaryService.java
  src/main/java/com/dailyemotion/domain/entity/Diary.java
  src/main/java/com/dailyemotion/user/controller/OAuthController.java
  src/main/java/com/dailyemotion/user/dto/request/TokenReqDto.java
  src/test/java/com/dailyemotion/dailyemotion/diary/controller/DiaryControllerTest.java
  src/test/java/com/dailyemotion/dailyemotion/diary/service/DiaryServiceTest.java
Labels: 🧪 test

#30 [Chore] swagger setting
  build.gradle
  src/main/java/com/dailyemotion/common/config/SecurityConfig.java
  src/main/java/com/dailyemotion/common/config/SwaggerConfig.java
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/java/com/dailyemotion/user/controller/UserController.java
  src/main/resources/application.yml
Labels: ✨ feat, 🔧 chore

#32 refactor : 개발환경, docker 서버 분리
  build.gradle
  docker-compose.yml
  dockerfile
  src/main/java/com/dailyemotion/common/exception/GlobalExceptionHandler.java
  src/main/java/com/dailyemotion/diary/controller/DiaryController.java
  src/main/resources/application.yml
  src/test/java/com/dailyemotion/dailyemotion/diary/controller/DiaryControllerTest.java
Labels: 🔧 chore

#33 Refactor/docker setup dockerfile 오타 수정
  dockerfile
Labels: ♻️ refactor
